package game;

public class Prog2CraftGame {

	Map map;
	
	public Prog2CraftGame() {
		
	map = Map.parse( "MMMMMMMMMMMMMMMMMMMMMM",
					 "MMMMMMMMMMMMMMMMMMMMMM",
					 "MMGGGGGGGGGGGGGGGGGGMM",
					 "MMGGGGGFFFFFFFFGGGGGMM",
					 "MMGGFFFFFFFFFFFFFFGGMM",
					 "MMGGFFLLLLLLLLLLFFGGMM",
					 "MMGFFLLLLLLLLLLLLFFGMM",
					 
					 "MMGFFLLLLLLLLLLLLFFGMM",
					 "MMGGFFLLLLLLLLLLFFGGMM",
					 "MMGGFFFFFFFFFFFFFFGGMM",
					 "MMGGGGGFFFFFFFFGGGGGMM",
					 "MMGGGGGGGGGGGGGGGGGGMM",
					 "MMMMMMMMMMMMMMMMMMMMMM",
					 "MMMMMMMMMMMMMMMMMMMMMM" );

	}
	
}
